name: CI

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  # When a PR happens OR code is pushed to main, start a job called validate,
  # run it on an Ubuntu machine, and first download my repository onto that machine.
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python with the default version for the workflow.
      - name: Set up Python
        uses: actions/setup-python@v5

      # Install Poetry to manage project dependencies and build the Python package.
      - name: Install Poetry
        run: pip install poetry

      # Install the project dependencies using the locked versions from poetry.lock.
      - name: Install dependencies
        run: poetry install